# Generated by Django 6.0.2 on 2026-04-01 00:04

from django.db import migrations, models


def mark_existing_users_onboarded(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.all().update(onboarding_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_users_onboarded,
            migrations.RunPython.noop,
        ),
    ]
