export const translations = {
  en: {
    appSettings: "App Settings",
    theme: "Theme",
    chooseAppearance: "Choose the appearance of the app",
    light: "Light",
    dark: "Night Blue",
    language: "Language",
    selectLanguage: "Choose your preferred language",
    notifications: "Notifications",
    enableNotifications: "Turn app notifications on or off",
    saveSettings: "Save settings",
    settingsSaved: "Settings saved",
    dashboard: "Dashboard",
    tasks: "Tasks",
    statistic: "Statistics",
    addNew: "Add New",
    community: "Community",
    settings: "Settings",
    logout: "Log out",
    yourProfile: "Your Profile",
    continueJourney: "Keep moving forward",
    achieveTarget: "and reach your goal",
    today: "Today",
    level: "Level",
    goal: "Goal",
    activeStatus: "Active",
    noGoals: "No goals yet",
    createFirstGoal: "Create your first goal in Add New.",
    completedTasks: "Completed Tasks",
    days: "Days",
    tasksForToday: "Tasks for today",
    noTasksToday: "No tasks for today yet.",
    otherGoals: "Other goals",
    noOtherGoals: "No other goals yet.",
    delete: "Delete",
    deleteGoal: "Delete goal",
    noDescription: "No description",
    deleteTaskConfirm: "Delete this task?",
    deleteGoalConfirm: "Delete this goal and all its tasks?",
    communityTitle: "Community",
    communityText: "Share progress, follow friends, and stay motivated together.",
    publication: "Publication",
    searchPlaceholder: "Search by author or post text",
    friends: "Friends",
    openFriendsList: "Open friends list",
    allPosts: "All posts",
    onlyFriends: "Friends only",
    myPosts: "My posts",
    noPostsYet: "No posts yet",
    createFirstPost: "Create your first publication or complete a task from Dashboard.",
    createPublication: "Create publication",
    shareProgress: "Share your progress with the community.",
    publicPost: "Public post",
    writeSomething: "Write something inspiring...",
    cancel: "Cancel",
    share: "Share",
    friendsList: "Friends list",
    manageFriends: "Manage your friends here.",
    writeUsername: "Enter username",
    addFriend: "Add friend",
    noFriendsYet: "No friends yet",
    blocked: "Blocked",
    friend: "Friend",
    unfriend: "Remove",
    block: "Block",
    friendExists: "This friend is already in the list",
    writeSomethingFirst: "Write something first",
    createNewTarget: "Create a new goal",
    buildGoalSubtitle: "Build a goal, set a deadline, and complete tasks to level up.",
    category: "Category",
    chooseCategory: "Choose category",
    habitName: "Goal name",
    description: "Description",
    definePeriod: "Set your own period",
    startDate: "Start date",
    endDate: "End date",
    habitTip1: "On average, it takes 66 days to build a habit, not 21.",
    habitTip2: "The exact period depends on the action and the person.",
    create: "Create",
    fillRequiredFields: "Please fill in all required fields",
    goalCreated: "Goal created successfully",
    noActiveGoal: "No active goal",
    createGoalFirst: "Create a goal in Add New first.",
    firstCreateGoal: "Create a goal first",
    fillTaskAndTime: "Fill in the task and time",
    endTimeLater: "End time must be later than start time",
    taskDateInsideGoal: "The task date must be within the goal period",
    writeGoalAi: "Describe your goal and I will suggest tasks for the selected day.",
    aiGeneratedForDay: "I generated tasks for",
    selectedDate: "Selected date",
    noTasksForDate: "No tasks for this date yet.",
    writeTask: "Write the task",
    chooseTime: "Choose time",
    addTask: "Add task",
    writeYourGoal: "Write your goal",
    generateWithAi: "Generate with AI",
    warmUpSession: "Warm-up session",
    mainExerciseBlock: "Main exercise block",
    stretching: "Stretching",
    statisticsOverview: "Statistics Overview",
    statisticsSubtitle: "Your progress updates automatically from completed tasks.",
    weeklyStudies: "Completed tasks over time",
    totalPerfectDays: "Completed tasks",
    averagePerDay: "Average per day",
    habitCompletionRate: "Task completion rate",
    totalHabitsBuilt: "Total goals",
    quickSummary: "Quick summary",
    totalTasks: "Total tasks",
    totalXpEarned: "Total XP earned",
    bestDayScore: "Best day score",
    range7: "Last 7 Days",
    range15: "Last 15 Days",
    range30: "Last 30 Days",
    range90: "Last 3 Months",
    range180: "Last 6 Months",
    range365: "Last Year",
    profilePhotoUpdated: "Profile photo updated",
    profilePhotoRemoved: "Profile photo removed",
    profileSaved: "Profile saved",
    uploadImageFile: "Please upload an image file",
    cardNumberError: "Card number must contain 16 digits",
    cardHolderRequired: "Card holder name is required",
    expiryError: "Expiry date must be in MM/YY format",
    cvvError: "CVV must contain 3 digits",
    subscriptionActivated: "Subscription activated successfully",
    changePhoto: "Change photo",
    remove: "Remove",
    name: "Name",
    emailAccount: "Email account",
    mobileNumber: "Mobile number",
    location: "Location",
    selectCity: "Select city",
    status: "Status",
    aboutMe: "About me",
    enterFullName: "Enter your full name",
    enterEmail: "Enter your email",
    addNumber: "Add number",
    writeStatus: "Write your status",
    tellAboutYourself: "Tell something about yourself",
    saveChange: "Save changes",
    paymentDetails: "Payment details",
    individualSubscription: "Individual subscription",
    monthFreeSubscription: "1 month free subscription",
    moreFeatures: "More features",
    cancelAnytime: "Cancel anytime",
    dollarsPerMonth: "$5 per month",
    subscribe: "Subscribe",
    enterCardData: "Enter your card data to activate premium subscription",
    cardNumber: "Card number",
    cardHolderName: "Card holder name",
    show: "Show",
    hide: "Hide",
    payFive: "Pay $5",
    cityAlmaty: "Almaty",
    cityAstana: "Astana",
    cityShymkent: "Shymkent",
    cityKaraganda: "Karaganda",
    cityAktobe: "Aktobe"
  },
  ru: {
    appSettings: "Настройки приложения",
    theme: "Тема",
    chooseAppearance: "Выберите внешний вид приложения",
    light: "Светлая",
    dark: "Ночной синий",
    language: "Язык",
    selectLanguage: "Выберите предпочтительный язык",
    notifications: "Уведомления",
    enableNotifications: "Включить или отключить уведомления приложения",
    saveSettings: "Сохранить настройки",
    settingsSaved: "Настройки сохранены",
    dashboard: "Дашборд",
    tasks: "Задачи",
    statistic: "Статистика",
    addNew: "Добавить",
    community: "Сообщество",
    settings: "Настройки",
    logout: "Выйти",
    yourProfile: "Ваш профиль",
    continueJourney: "Продолжай свой путь",
    achieveTarget: "и достигай своей цели",
    today: "Сегодня",
    level: "Уровень",
    goal: "Цель",
    activeStatus: "Активна",
    noGoals: "Целей пока нет",
    createFirstGoal: "Создайте свою первую цель в разделе «Добавить».",
    completedTasks: "Выполненные задачи",
    days: "Дни",
    tasksForToday: "Задачи на сегодня",
    noTasksToday: "На сегодня задач пока нет.",
    otherGoals: "Другие цели",
    noOtherGoals: "Других целей пока нет.",
    delete: "Удалить",
    deleteGoal: "Удалить цель",
    noDescription: "Нет описания",
    deleteTaskConfirm: "Удалить эту задачу?",
    deleteGoalConfirm: "Удалить эту цель и все её задачи?",
    communityTitle: "Сообщество",
    communityText: "Делитесь прогрессом, следите за друзьями и мотивируйте друг друга.",
    publication: "Публикация",
    searchPlaceholder: "Поиск по автору или тексту публикации",
    friends: "Друзья",
    openFriendsList: "Открыть список друзей",
    allPosts: "Все посты",
    onlyFriends: "Только друзья",
    myPosts: "Мои посты",
    noPostsYet: "Постов пока нет",
    createFirstPost: "Создайте первую публикацию или выполните задачу в дашборде.",
    createPublication: "Создать публикацию",
    shareProgress: "Поделитесь своим прогрессом с сообществом.",
    publicPost: "Публичный пост",
    writeSomething: "Напишите что-нибудь вдохновляющее...",
    cancel: "Отмена",
    share: "Поделиться",
    friendsList: "Список друзей",
    manageFriends: "Управляйте друзьями здесь.",
    writeUsername: "Введите username",
    addFriend: "Добавить друга",
    noFriendsYet: "Друзей пока нет",
    blocked: "Заблокирован",
    friend: "Друг",
    unfriend: "Удалить",
    block: "Блок",
    friendExists: "Этот друг уже есть в списке",
    writeSomethingFirst: "Сначала введите текст",
    createNewTarget: "Создать новую цель",
    buildGoalSubtitle: "Соберите цель, задайте дедлайн и выполняйте задачи, чтобы повышать уровень.",
    category: "Категория",
    chooseCategory: "Выберите категорию",
    habitName: "Название цели",
    description: "Описание",
    definePeriod: "Задайте свой период",
    startDate: "Дата начала",
    endDate: "Дата окончания",
    habitTip1: "В среднем на формирование привычки уходит 66 дней, а не 21.",
    habitTip2: "Точный срок зависит от самого действия и человека.",
    create: "Создать",
    fillRequiredFields: "Пожалуйста, заполните все обязательные поля",
    goalCreated: "Цель успешно создана",
    noActiveGoal: "Нет активной цели",
    createGoalFirst: "Сначала создайте цель в разделе «Добавить».",
    firstCreateGoal: "Сначала создайте цель",
    fillTaskAndTime: "Заполните задачу и время",
    endTimeLater: "Время окончания должно быть позже времени начала",
    taskDateInsideGoal: "Дата задачи должна быть в пределах периода цели",
    writeGoalAi: "Опишите цель, и я предложу задачи на выбранный день.",
    aiGeneratedForDay: "Я сгенерировал задачи на",
    selectedDate: "Выбранная дата",
    noTasksForDate: "На эту дату задач пока нет.",
    writeTask: "Введите задачу",
    chooseTime: "Выберите время",
    addTask: "Добавить задачу",
    writeYourGoal: "Опишите цель",
    generateWithAi: "Сгенерировать с AI",
    warmUpSession: "Разминка",
    mainExerciseBlock: "Основной блок",
    stretching: "Растяжка",
    statisticsOverview: "Обзор статистики",
    statisticsSubtitle: "Ваш прогресс обновляется автоматически по выполненным задачам.",
    weeklyStudies: "Выполненные задачи по дням",
    totalPerfectDays: "Выполненные задачи",
    averagePerDay: "Среднее в день",
    habitCompletionRate: "Процент выполнения задач",
    totalHabitsBuilt: "Всего целей",
    quickSummary: "Краткая сводка",
    totalTasks: "Всего задач",
    totalXpEarned: "Всего XP",
    bestDayScore: "Лучший день",
    range7: "Последние 7 дней",
    range15: "Последние 15 дней",
    range30: "Последние 30 дней",
    range90: "Последние 3 месяца",
    range180: "Последние 6 месяцев",
    range365: "Последний год",
    profilePhotoUpdated: "Фото профиля обновлено",
    profilePhotoRemoved: "Фото профиля удалено",
    profileSaved: "Профиль сохранён",
    uploadImageFile: "Пожалуйста, загрузите файл изображения",
    cardNumberError: "Номер карты должен содержать 16 цифр",
    cardHolderRequired: "Укажите имя владельца карты",
    expiryError: "Срок действия должен быть в формате ММ/ГГ",
    cvvError: "CVV должен содержать 3 цифры",
    subscriptionActivated: "Подписка успешно активирована",
    changePhoto: "Изменить фото",
    remove: "Удалить",
    name: "Имя",
    emailAccount: "Почта",
    mobileNumber: "Телефон",
    location: "Город",
    selectCity: "Выберите город",
    status: "Статус",
    aboutMe: "О себе",
    enterFullName: "Введите полное имя",
    enterEmail: "Введите email",
    addNumber: "Добавьте номер",
    writeStatus: "Напишите статус",
    tellAboutYourself: "Расскажите немного о себе",
    saveChange: "Сохранить",
    paymentDetails: "Платёжные данные",
    individualSubscription: "Индивидуальная подписка",
    monthFreeSubscription: "1 месяц бесплатно",
    moreFeatures: "Больше возможностей",
    cancelAnytime: "Можно отменить в любое время",
    dollarsPerMonth: "$5 в месяц",
    subscribe: "Подписаться",
    enterCardData: "Введите данные карты, чтобы активировать премиум-подписку",
    cardNumber: "Номер карты",
    cardHolderName: "Имя владельца карты",
    show: "Показать",
    hide: "Скрыть",
    payFive: "Оплатить $5",
    cityAlmaty: "Алматы",
    cityAstana: "Астана",
    cityShymkent: "Шымкент",
    cityKaraganda: "Караганда",
    cityAktobe: "Актобе"
  },
  kz: {
    appSettings: "Қолданба баптаулары",
    theme: "Тақырып",
    chooseAppearance: "Қолданбаның көрінісін таңдаңыз",
    light: "Жарық",
    dark: "Түнгі көк",
    language: "Тіл",
    selectLanguage: "Қалаған тілді таңдаңыз",
    notifications: "Хабарламалар",
    enableNotifications: "Қолданба хабарламаларын қосу немесе өшіру",
    saveSettings: "Баптауларды сақтау",
    settingsSaved: "Баптаулар сақталды",
    dashboard: "Басқару панелі",
    tasks: "Тапсырмалар",
    statistic: "Статистика",
    addNew: "Қосу",
    community: "Қауымдастық",
    settings: "Баптаулар",
    logout: "Шығу",
    yourProfile: "Сіздің профиліңіз",
    continueJourney: "Жолыңызды жалғастырыңыз",
    achieveTarget: "және мақсатыңызға жетіңіз",
    today: "Бүгін",
    level: "Деңгей",
    goal: "Мақсат",
    activeStatus: "Белсенді",
    noGoals: "Әзірге мақсаттар жоқ",
    createFirstGoal: "Алғашқы мақсатыңызды «Қосу» бөлімінде жасаңыз.",
    completedTasks: "Орындалған тапсырмалар",
    days: "Күндер",
    tasksForToday: "Бүгінгі тапсырмалар",
    noTasksToday: "Бүгінге тапсырма әлі жоқ.",
    otherGoals: "Басқа мақсаттар",
    noOtherGoals: "Басқа мақсаттар әлі жоқ.",
    delete: "Жою",
    deleteGoal: "Мақсатты жою",
    noDescription: "Сипаттама жоқ",
    deleteTaskConfirm: "Осы тапсырманы жою керек пе?",
    deleteGoalConfirm: "Осы мақсат пен оның барлық тапсырмаларын жою керек пе?",
    communityTitle: "Қауымдастық",
    communityText: "Прогресіңізбен бөлісіңіз, достарыңызды бақылаңыз және бірге мотивация алыңыз.",
    publication: "Жарияланым",
    searchPlaceholder: "Автор немесе жарияланым мәтіні бойынша іздеу",
    friends: "Достар",
    openFriendsList: "Достар тізімін ашу",
    allPosts: "Барлық посттар",
    onlyFriends: "Тек достар",
    myPosts: "Менің посттарым",
    noPostsYet: "Посттар әлі жоқ",
    createFirstPost: "Алғашқы жарияланымды жасаңыз немесе дашбордта тапсырма орындаңыз.",
    createPublication: "Жарияланым жасау",
    shareProgress: "Прогресіңізді қауымдастықпен бөлісіңіз.",
    publicPost: "Ашық пост",
    writeSomething: "Шабыттандыратын нәрсе жазыңыз...",
    cancel: "Бас тарту",
    share: "Бөлісу",
    friendsList: "Достар тізімі",
    manageFriends: "Достарыңызды осы жерден басқарыңыз.",
    writeUsername: "Username енгізіңіз",
    addFriend: "Дос қосу",
    noFriendsYet: "Достар әлі жоқ",
    blocked: "Бұғатталған",
    friend: "Дос",
    unfriend: "Өшіру",
    block: "Бұғаттау",
    friendExists: "Бұл дос тізімде бар",
    writeSomethingFirst: "Алдымен мәтін жазыңыз",
    createNewTarget: "Жаңа мақсат құру",
    buildGoalSubtitle: "Мақсат құрып, мерзім қойып, деңгей көтеру үшін тапсырмалар орындаңыз.",
    category: "Санат",
    chooseCategory: "Санатты таңдаңыз",
    habitName: "Мақсат атауы",
    description: "Сипаттама",
    definePeriod: "Өз кезеңіңізді белгілеңіз",
    startDate: "Басталу күні",
    endDate: "Аяқталу күні",
    habitTip1: "Әдет қалыптастыруға орта есеппен 21 емес, 66 күн қажет.",
    habitTip2: "Нақты уақыт әрекет пен адамға байланысты.",
    create: "Құру",
    fillRequiredFields: "Барлық міндетті өрістерді толтырыңыз",
    goalCreated: "Мақсат сәтті құрылды",
    noActiveGoal: "Белсенді мақсат жоқ",
    createGoalFirst: "Алдымен «Қосу» бөлімінде мақсат жасаңыз.",
    firstCreateGoal: "Алдымен мақсат жасаңыз",
    fillTaskAndTime: "Тапсырма мен уақытты толтырыңыз",
    endTimeLater: "Аяқталу уақыты басталу уақытынан кейін болуы керек",
    taskDateInsideGoal: "Тапсырма күні мақсат кезеңінің ішінде болуы керек",
    writeGoalAi: "Мақсатыңызды жазыңыз, мен таңдалған күнге тапсырмалар ұсынамын.",
    aiGeneratedForDay: "Мен мына күнге тапсырмалар құрдым",
    selectedDate: "Таңдалған күн",
    noTasksForDate: "Бұл күнге әлі тапсырма жоқ.",
    writeTask: "Тапсырманы жазыңыз",
    chooseTime: "Уақытты таңдаңыз",
    addTask: "Тапсырма қосу",
    writeYourGoal: "Мақсатыңызды жазыңыз",
    generateWithAi: "AI арқылы құру",
    warmUpSession: "Жылынып алу",
    mainExerciseBlock: "Негізгі бөлім",
    stretching: "Созылу",
    statisticsOverview: "Статистика шолуы",
    statisticsSubtitle: "Прогресіңіз орындалған тапсырмалар бойынша автоматты жаңарады.",
    weeklyStudies: "Күндер бойынша орындалған тапсырмалар",
    totalPerfectDays: "Орындалған тапсырмалар",
    averagePerDay: "Күніне орташа",
    habitCompletionRate: "Тапсырма орындау пайызы",
    totalHabitsBuilt: "Барлық мақсаттар",
    quickSummary: "Қысқаша қорытынды",
    totalTasks: "Барлық тапсырмалар",
    totalXpEarned: "Жиналған XP",
    bestDayScore: "Ең жақсы күн",
    range7: "Соңғы 7 күн",
    range15: "Соңғы 15 күн",
    range30: "Соңғы 30 күн",
    range90: "Соңғы 3 ай",
    range180: "Соңғы 6 ай",
    range365: "Соңғы жыл",
    profilePhotoUpdated: "Профиль фотосы жаңартылды",
    profilePhotoRemoved: "Профиль фотосы өшірілді",
    profileSaved: "Профиль сақталды",
    uploadImageFile: "Сурет файлын жүктеңіз",
    cardNumberError: "Карта нөмірі 16 цифрдан тұруы керек",
    cardHolderRequired: "Карта иесінің атын енгізіңіз",
    expiryError: "Жарамдылық мерзімі АА/ЖЖ форматында болуы керек",
    cvvError: "CVV 3 цифрдан тұруы керек",
    subscriptionActivated: "Жазылым сәтті қосылды",
    changePhoto: "Фотоны өзгерту",
    remove: "Жою",
    name: "Аты",
    emailAccount: "Email",
    mobileNumber: "Телефон",
    location: "Қала",
    selectCity: "Қаланы таңдаңыз",
    status: "Мәртебе",
    aboutMe: "Өзім туралы",
    enterFullName: "Толық атыңызды енгізіңіз",
    enterEmail: "Email енгізіңіз",
    addNumber: "Нөмір қосыңыз",
    writeStatus: "Мәртебе жазыңыз",
    tellAboutYourself: "Өзіңіз туралы жазыңыз",
    saveChange: "Сақтау",
    paymentDetails: "Төлем деректері",
    individualSubscription: "Жеке жазылым",
    monthFreeSubscription: "1 ай тегін жазылым",
    moreFeatures: "Көбірек мүмкіндік",
    cancelAnytime: "Кез келген уақытта тоқтатуға болады",
    dollarsPerMonth: "Айына $5",
    subscribe: "Жазылу",
    enterCardData: "Премиум жазылымды қосу үшін карта деректерін енгізіңіз",
    cardNumber: "Карта нөмірі",
    cardHolderName: "Карта иесінің аты",
    show: "Көрсету",
    hide: "Жасыру",
    payFive: "$5 төлеу",
    cityAlmaty: "Алматы",
    cityAstana: "Астана",
    cityShymkent: "Шымкент",
    cityKaraganda: "Қарағанды",
    cityAktobe: "Ақтөбе"
  }
};

export const readStoredJson = (key, fallback) => {
  const rawValue = localStorage.getItem(key);

  if (!rawValue) {
    return fallback;
  }

  try {
    const parsed = JSON.parse(rawValue);
    return parsed ?? fallback;
  } catch {
    return fallback;
  }
};

export const getAppSettings = () => {
  return readStoredJson("appSettings", {
    theme: "light",
    language: "en",
    notifications: true,
  });
};

export const getLang = () => {
  return getAppSettings().language || "en";
};

export const getLocale = () => {
  const lang = getLang();
  if (lang === "ru") return "ru-RU";
  if (lang === "kz") return "kk-KZ";
  return "en-US";
};

export const t = () => {
  const lang = getLang();
  return translations[lang] || translations.en;
};

export const applyTheme = (theme) => {
  document.body.classList.remove("light-theme", "dark-theme");
  document.body.classList.add(theme === "dark" ? "dark-theme" : "light-theme");
  document.documentElement.classList.remove("light-theme", "dark-theme");
  document.documentElement.classList.add(theme === "dark" ? "dark-theme" : "light-theme");
};
